In [1]:
##this script is to plot B4 and Density
#relax structue from full simulaton final data file
#'10 K/ps', '1 K/ps', '0.1 K/ps','100 K/ps' are [3,2,1,4]: respectivaly

#0.1 K/ps--> 3
#1 K/ps--> 2
#10 K/ps--> 1
#100 K/ps--> 4

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib 

plt.rc('font', family='CMU Serif',)

matplotlib.rcParams['text.latex.preamble'] = [r'\boldmath']

EXP = np.loadtxt("NABS_EXP.txt")


fig, (ax1,ax2) = plt.subplots(2,1,figsize=[8,11])
data = []
names = []
df = []
ttl=['al0','al1','al2.5','al5','al7.5','al10','al12.5','al15','al17.5','al20']
leg=['10 K/ps', '1 K/ps', '0.1 K/ps','100 K/ps']
ax1.plot(ttl,EXP[:,2],label='EXP')
ax2.plot(ttl,EXP[:,5],label='EXP')

for i in [3,2,1,4]:
    b=[] 
    d=[]
    
    for j in range(1,11):
        if (i==4)&(j==7):
            b.append(b[-1])
            d.append(d[-1])
            #pass
        else:
            #print(i)
            foldername = '/Users/rajesh/work/simulations/cool_NABS_relax/relax10K/cool'+str(j)+'_'+str(i)
            filename = foldername +'/log.lammps'
            #print(filename)
            a = [181, 1, 190, 2]  
            #names.append(np.genfromtxt(filename, skip_header=a[0],max_rows=a[1],dtype=str))   
            #print(names)
            data.append(np.genfromtxt(filename, skip_header=a[2],max_rows=a[3],dtype=float))   
            #print(names[i-1])
            #print(data[i-1])
            #df.append(pd.DataFrame(data[i-1][-1]),columns=names[i-1][-1])
            bb=data[-1][-1][-1]
            dd=data[-1][-1][-2]
            b.append((bb-3)*100) #changed to array by .values
        
            d.append(dd)
                
                
                
                
    ax1.set_ylabel('B4')
    ax2.set_ylabel('Density')
    ax1.set_xlabel('Al %')
    ax2.set_xlabel('Al %')
   
    ax1.plot(ttl,b,label=str(leg[i-1]))
    
    ax2.plot(ttl,d,label=str(leg[i-1]))
ax1.legend()
ax2.legend()



fig.savefig('B4_vs_rex.eps',format=None,dpi=300,bbox_inches="tight")        

        


In [2]:
data[-1][-1]

array([ 1.9000000e+04,  3.0312628e+02, -8.1177078e+05, -1.0405893e+03,
        3.6242380e+01,  2.4846517e+00,  3.1764706e+00])

In [3]:
 data[-1][-1][-2]
a

[181, 1, 190, 2]

In [4]:
EXP = np.loadtxt("NABS_EXP.txt")

In [5]:
EXP[:,2]

array([94.9, 93.2, 94.6, 91.6, 83.1, 74.4, 43.6, 19.9,  1. ,  0.8])

In [6]:
EXP[:,5]

array([2.3955, 2.4194, 2.4078, 2.3961, 2.4069, 2.4038, 2.3899, 2.385 ,
       2.3809, 2.3687])

In [17]:

cd /Users/rajesh/work/github/helloword

NameError: name 'cd' is not defined

In [23]:
# This script reads a GPS track in CSV format and
#  prints a list of coordinate pairs
import csv
 
# Set up input and output variables for the script
gpsTrack = open("/Users/rajesh/work/github/helloword/gps_track.txt", "r")
print(gpsTrack)
# Set up CSV reader and process the header
csvReader = csv.reader(gpsTrack)
header = csvReader.next()
latIndex = header.index("lat")
lonIndex = header.index("long")
 
# Make an empty list
coordList = []
 
# Loop through the lines in the file and get each coordinate
for row in csvReader:
    lat = row[latIndex]
    lon = row[lonIndex]
    coordList.append([lat,lon])
 
# Print the coordinate list
print (coordList)

<_io.TextIOWrapper name='/Users/rajesh/work/github/helloword/gps_track.txt' mode='r' encoding='UTF-8'>


AttributeError: '_csv.reader' object has no attribute 'next'

In [20]:
%pwd

'/Users/rajesh'

In [13]:
cd ../Desktop

[Errno 2] No such file or directory: '../Desktop'
/Users/rajesh
