In [54]:
%run script.py
!cat -n  script.py

     1	#!echo "hello python"
     2	import pandas as pd
     3	import numpy as np
     4	import matplotlib.pyplot as plt
     5	import matplotlib 
     6	matplotlib.rcParams['text.latex.preamble'] = [r'\boldmath']
     7	import sys
     8	sys.path.append("/Users/rajesh/work/github/python_packages")


In [55]:
x = np.array([1,2,3])
x.itemsize
np.sin(x)

array([0.84147098, 0.90929743, 0.14112001])

In [56]:
pwd

'/Users/rajesh/work/github/helloword'

In [57]:
cd ../

/Users/rajesh/work/github


In [58]:
pwd

'/Users/rajesh/work/github'

In [59]:
import lmps.log as log
tables = log.reader('log.lammps')
!pwd


/Users/rajesh/work/github


In [60]:
!tail log.lammps

   63000    2940.0406   -539142.45    2631.9553    40.487214     2.020901 
   64000    3005.2173   -538122.48   -1296.3465    40.528008    2.0148046 
   65000    2930.7983   -538002.76   -2005.3159    40.514786    2.0167779 
   66000    3028.5625    -539032.6   -982.19953     40.44742    2.0268716 
   67000    2924.6372   -538583.29    4031.6264    40.457572    2.0253462 
   68000    3017.1608   -538640.71   -6443.3127    40.590075    2.0055762 
   69000     3017.128      -539032   -1617.9181    40.495635    2.0196405 
   70000    2922.8512   -539474.11      1759.18    40.442655    2.0275881 
ERROR: Lost atoms: original 4004 current 4003 (../thermo.cpp:442)
Last command: run 2700000


In [61]:
tables.keys()
tables['label'][-1]
tables['df'][-1]

Step       Temp     PotEng        Press         Lx   Density
0   50000.0  2957.7802 -538067.14  6267.109500  40.484337  2.021332
1   51000.0  2953.3810 -538493.85  7698.582900  40.394294  2.034879
2   52000.0  2981.1085 -538899.43 -1710.209200  40.461200  2.024801
3   53000.0  3043.8697 -538183.82  1518.864800  40.441690  2.027733
4   54000.0  2986.0383 -538272.53 -2725.666800  40.591784  2.005323
5   55000.0  2981.8617 -538370.10    62.257118  40.429824  2.029519
6   56000.0  2987.7479 -538695.30 -3489.927300  40.543211  2.012539
7   57000.0  3041.0665 -537398.30  5544.245000  40.558898  2.010205
8   58000.0  2981.8630 -538000.90 -4185.785800  40.572963  2.008115
9   59000.0  3040.7966 -537600.49  4856.977100  40.583541  2.006545
10  60000.0  2954.9709 -537874.99 -2589.257600  40.498595  2.019198
11  61000.0  2985.5599 -537783.26 -4463.457000  40.558723  2.010231
12  62000.0  3025.7805 -538083.91  1196.352900  40.529947  2.014515
13  63000.0  2940.0406 -539142.45  2631.955300  40.487214  2.020901
14  64000.0  3005.2173 -538122.48 -1296.346500  40.528008  2.014805
15  65000.0  2930.7983 -538002.76 -2005.315900  40.514786  2.016778
16  66000.0  3028.5625 -539032.60  -982.199530  40.447420  2.026872
17  67000.0  2924.6372 -538583.29  4031.626400  40.457572  2.025346
18  68000.0  3017.1608 -538640.71 -6443.312700  40.590075  2.005576
19  69000.0  3017.1280 -539032.00 -1617.918100  40.495635  2.019640
20  70000.0  2922.8512 -539474.11  1759.180000  40.442655  2.027588

In [62]:
np.sin(np.array([90.0 ,180.0, 270.0])/180*3.14,dtype=np.float32)

array([ 0.9999997 ,  0.00159255, -0.99999714], dtype=float32)

In [63]:
from math import sin
[sin(i) for i in [3.14,1,3]]

[0.0015926529164868282, 0.8414709848078965, 0.1411200080598672]

In [64]:
type(x)
x=(np.array( [1,2,3]))

In [65]:
print(x)
x.shape
x[2]

[1 2 3]


3

In [81]:
x=np.array([ [1,2,3],[4,5,6] ])

In [85]:
x[:,1:] # all rows, 1st thru last column

array([[2, 3],
       [5, 6]])

In [86]:
x[:,::2] # all rows, every other column

array([[1, 3],
       [4, 6]])

In [87]:
x[:,::-1] # reverse order of columns

array([[3, 2, 1],
       [6, 5, 4]])

In [88]:
x=ones(3,3)

NameError: name 'ones' is not defined